# This Dockerfile contains a docker container configuration
# for redstone cache layer express app with the light mode
# So the app doesn't store historical data and uses
# memory as a storage instead of Mongo DB

FROM public.ecr.aws/lambda/nodejs:14

WORKDIR /var/task/

COPY package.json package.json
COPY yarn.lock yarn.lock
RUN npm i -g yarn
RUN yarn

COPY . .

ENV MODE=PROD

ENV LIGHT_MODE = true

CMD [ "index.handler" ]
